"use client";

import Image, { type ImageProps } from "next/image";
import { useState } from "react";
import { blurFor } from "@/lib/image-blur";

/**
 * next/image with a blur-up placeholder and a fade on decode.
 *
 * Without this, images pop in: there was no placeholder, skeleton or fade
 * anywhere outside the product gallery. The placeholders come from the LQIP
 * manifest generated by scripts/optimize-images.mjs, so no extra request is
 * made - each is a ~20px WebP inlined as a data URI.
 *
 * Falls back to a plain image when the source is not in the manifest (a remote
 * URL, or a file added without re-running the script).
 */
export default function Photo({
  src,
  alt,
  className,
  fadeIn = true,
  ...rest
}: ImageProps & { fadeIn?: boolean }) {
  const [loaded, setLoaded] = useState(false);
  const blurDataURL = typeof src === "string" ? blurFor(src) : undefined;

  return (
    <Image
      {...rest}
      src={src}
      alt={alt}
      className={[
        className,
        fadeIn ? "photo-fade" : null,
        fadeIn && loaded ? "is-loaded" : null,
      ]
        .filter(Boolean)
        .join(" ")}
      {...(blurDataURL ? { placeholder: "blur" as const, blurDataURL } : {})}
      onLoad={() => setLoaded(true)}
    />
  );
}
