import Image, { type ImageProps } from "next/image";
import { blurFor } from "@/lib/image-blur";

/**
 * next/image with a blur-up placeholder.
 *
 * Without this, images popped in: there was no placeholder, skeleton or fade
 * anywhere outside the product gallery. The placeholders come from the LQIP
 * manifest generated by scripts/optimize-images.mjs, so no extra request is
 * made - each is a ~20px WebP inlined as a data URI, and next/image cross-fades
 * it out natively once the full image decodes.
 *
 * This deliberately holds no state. An earlier version tracked decode with
 * `onLoad` and a `loaded` flag, but for an image already in the browser cache
 * `onLoad` fires before the component mounts, which React reports as "Can't
 * perform a React state update on a component that hasn't mounted yet" and
 * which broke hydration on pages carrying many images. The native placeholder
 * transition gives the same result with no state at all, so this is also a
 * Server Component and ships no JavaScript.
 *
 * Falls back to a plain image when the source is not in the manifest (a remote
 * URL, or a file added without re-running the script).
 */
export default function Photo({
  src,
  alt,
  ...rest
}: ImageProps & { fadeIn?: boolean }) {
  // `fadeIn` is accepted and ignored: callers used it to opt out of the old
  // JS fade, and the native transition needs no opt-out.
  const { fadeIn, ...imageProps } = rest as ImageProps & {
    fadeIn?: boolean;
  };
  void fadeIn;
  const blurDataURL = typeof src === "string" ? blurFor(src) : undefined;

  return (
    <Image
      {...imageProps}
      src={src}
      alt={alt}
      {...(blurDataURL ? { placeholder: "blur" as const, blurDataURL } : {})}
    />
  );
}
