/**
 * Converts the camera-original photography under public/ into web-ready WebP and
 * records a low-quality image placeholder (LQIP) for each one.
 *
 * The storefront was serving up to 7.4 MB per image. next/image re-encodes on
 * demand, but it still has to read and decode the original every time, so the
 * originals are downsized here once instead.
 *
 * Usage:
 *   node scripts/optimize-images.mjs           # convert, write LQIP manifest
 *   node scripts/optimize-images.mjs --check    # report only, change nothing
 *
 * Originals are never deleted by this script. Move them to assets-source/ by
 * hand once you have verified the generated files.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const PUBLIC = join(ROOT, "public");
const MANIFEST = join(ROOT, "src", "lib", "image-blur.ts");

/** Longest edge kept in the generated file. Beyond this, next/image downscales anyway. */
const MAX_EDGE = 2400;
const QUALITY = 82;
/** Width of the inlined blur placeholder. Kept tiny so the data URI stays short. */
const LQIP_WIDTH = 20;

const checkOnly = process.argv.includes("--check");

const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    return entry.isDirectory() ? walk(path) : [path];
  });

const toWebPath = (abs) => "/" + relative(PUBLIC, abs).split(sep).join("/");
const mb = (bytes) => (bytes / 1048576).toFixed(2) + " MB";

const originals = walk(PUBLIC).filter((file) => /\.(jpe?g)$/i.test(file));

let savedBytes = 0;
const blur = {};

for (const source of originals) {
  const target = source.replace(/\.(jpe?g)$/i, ".webp");
  const before = statSync(source).size;

  if (!checkOnly) {
    await sharp(source)
      .rotate() // honour EXIF orientation before stripping metadata
      .resize({
        width: MAX_EDGE,
        height: MAX_EDGE,
        fit: "inside",
        withoutEnlargement: true,
      })
      .webp({ quality: QUALITY })
      .toFile(target);
  }

  const after = checkOnly ? before : statSync(target).size;
  savedBytes += before - after;
  console.log(
    `${toWebPath(source)}\n  ${mb(before)} -> ${mb(after)}  (${Math.round((1 - after / before) * 100)}% smaller)`,
  );
}

// Every raster asset the storefront can render gets a placeholder, including the
// .webp files that were already optimised and are not re-encoded above.
if (!checkOnly) {
  for (const file of walk(PUBLIC).filter((f) => /\.(webp|png)$/i.test(f))) {
    const data = await sharp(file)
      .resize({ width: LQIP_WIDTH })
      .webp({ quality: 45 })
      .toBuffer();
    blur[toWebPath(file)] = `data:image/webp;base64,${data.toString("base64")}`;
  }

  const entries = Object.keys(blur)
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(blur[key])},`)
    .join("\n");

  writeFileSync(
    MANIFEST,
    `// Generated by scripts/optimize-images.mjs — do not edit by hand.\n` +
      `// Base64 LQIP placeholders keyed by public path, for next/image blur-up.\n\n` +
      `export const IMAGE_BLUR: Record<string, string> = {\n${entries}\n};\n\n` +
      `export const blurFor = (src: string) => IMAGE_BLUR[src];\n`,
  );
  console.log(
    `\nLQIP manifest: ${Object.keys(blur).length} entries -> ${relative(ROOT, MANIFEST)}`,
  );
}

console.log(
  `\nTotal saved: ${mb(savedBytes)} across ${originals.length} images`,
);
